// Official squad members with confirmed injury status as of June 3, 2026
// Only players who WERE in the official FIFA squad lists submitted by June 1, 2026

export const BASE_DATA = [
  {
    player: 'Billy Gilmour',
    team: 'Escocia',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    pos: 'Centrocampista',
    club: 'Napoli',
    status: 'out',
    injury: 'Lesión de rodilla en el amistoso vs Curazao (31 may). Salió en el min. 42. Baja oficial confirmada por la Federación Escocesa.',
    replacement: 'Tyler Fletcher (Manchester United Sub-21, 19 años)',
    timeline: 'Fuera del Mundial 2026. Regresa a Napoli para rehabilitación.',
    link: 'https://www.beinsports.com/en-us/soccer/fifa-world-cup-2026/articles/scotland-lose-billy-gilmour-before-the-2026-world-cup-after-knee-injury-in-major-blow-to-their-midfield-ahead-of-the-tournament-2026-05-31',
    link_label: 'beIN Sports — Baja oficial',
    confirmed_date: '31 may 2026',
  },
  {
    player: 'Cho Yumin',
    team: 'Corea del Sur',
    flag: '🇰🇷',
    pos: 'Defensa',
    club: 'Desconocido',
    status: 'out',
    injury: 'Baja por lesión comunicada a FIFA el 2 de junio, mismo día de la publicación oficial de convocatorias.',
    replacement: 'Cho Wije (convocado el 2 jun, aprobado por FIFA)',
    timeline: 'Fuera del Mundial 2026.',
    link: 'https://www.olympics.com/en/news/2026-fifa-world-cup-football-teams-squads-players-complete-list',
    link_label: 'Olympics.com — Cambio oficial FIFA',
    confirmed_date: '2 jun 2026',
  },
  {
    player: 'Christoph Baumgartner',
    team: 'Austria',
    flag: '🇦🇹',
    pos: 'Centrocampista',
    club: 'RB Leipzig',
    status: 'out',
    injury: 'Lesión durante la preparación para el torneo. Austria confirmó que no designará reemplazante.',
    replacement: null,
    timeline: 'Austria disputará el Mundial con 25 jugadores en lugar de 26.',
    link: 'https://www.skysports.com/football/news/12098/13543070/world-cup-2026-squad-lists-england-scotland-brazil-usa-spain-france-germany-netherlands-argentina-portugal-and-more',
    link_label: 'Sky Sports — Convocatoria Austria',
    confirmed_date: 'Jun 2026',
  },
  {
    player: 'Marcelo Flores',
    team: 'Canadá',
    flag: '🇨🇦',
    pos: 'Extremo / Mediapunta',
    club: 'Tigres UANL',
    status: 'out',
    injury: 'Rotura del LCA rodilla derecha en la final CONCACAF Champions Cup con Tigres (31 may), un día tras ser convocado oficialmente.',
    replacement: 'Pendiente — candidatos: Jayden Nelson (Austin FC) o Daniel Jebbison',
    timeline: 'Fuera del Mundial 2026. Cirugía programada. Marsch: "Devastated for him."',
    link: 'https://www.espn.com/soccer/story/_/id/48931912/canada-flores-says-acl-gone-world-cup-status-doubt',
    link_label: 'ESPN — Confirmación ACL roto',
    confirmed_date: '31 may – 1 jun 2026',
  },
  {
    player: 'Neymar Jr',
    team: 'Brasil',
    flag: '🇧🇷',
    pos: 'Delantero',
    club: 'Santos',
    status: 'doubt',
    injury: 'Desgarro muscular grado 2 en el gemelo derecho (17 may, Santos vs Coritiba). Se pierde los amistosos de preparación.',
    replacement: null,
    timeline: 'Ancelotti: "No cambio nada, los 26 van al Mundial." Se espera para el 13 jun (vs Marruecos) o el 2° partido.',
    link: 'https://www.espn.com/soccer/story/_/id/48922562/brazil-carlo-ancelotti-neymar-injury-2026-world-cup',
    link_label: 'ESPN — Ancelotti sobre Neymar',
    confirmed_date: 'May 2026',
  },
  {
    player: 'Lionel Messi',
    team: 'Argentina',
    flag: '🇦🇷',
    pos: 'Delantero',
    club: 'Inter Miami',
    status: 'doubt',
    injury: 'Molestia muscular en el muslo izquierdo (Inter Miami). Entrena de forma separada en Kansas City. 9 jugadores argentinos con alguna molestia.',
    replacement: null,
    timeline: 'Se espera disponible para debut vs Argelia (16 jun). Scaloni puede hacer cambios hasta el 15 jun.',
    link: 'https://sports.yahoo.com/soccer/live/2026-world-cup-news-live-tracker-injuries-squads-storylines-and-updates-as-the-tournament-looms-200000653.html',
    link_label: 'Yahoo Sports — Live tracker',
    confirmed_date: 'Jun 2026',
  },
  {
    player: 'Alphonso Davies',
    team: 'Canadá',
    flag: '🇨🇦',
    pos: 'Lateral izquierdo',
    club: 'Bayern Munich',
    status: 'doubt',
    injury: 'Lesión de isquiotibial en la semifinal de la Champions League con Bayern Munich. Convocado pese a la duda.',
    replacement: null,
    timeline: 'Disponibilidad para el debut vs Bosnia (12 jun) no garantizada. Capitán del equipo, sin sustituto natural.',
    link: 'https://www.sportsmole.co.uk/football/england/world-cup/feature/world-cup-2026-injury-watch-yamal-saliba-livramento-seven-players-battling-fitness-concerns-ahead-of-the-tournament_598546.html',
    link_label: 'Sports Mole — Estado Davies',
    confirmed_date: 'May–Jun 2026',
  },
  {
    player: 'Lamine Yamal',
    team: 'España',
    flag: '🇪🇸',
    pos: 'Extremo derecho',
    club: 'FC Barcelona',
    status: 'doubt',
    injury: 'Rotura muscular grado 2 bíceps femoral izquierdo (vs Celta, mayo 2026). 6–8 semanas de baja estimadas.',
    replacement: null,
    timeline: 'España confía en que llegue, aunque sin ritmo pleno. En seguimiento médico continuo.',
    link: 'https://depor.com/futbol-internacional/mundial/lesionados-que-no-iran-al-mundial-2026-jugadores-descartados-que-lesion-tienen-cual-es-la-lesion-mas-recurrente-y-quienes-si-se-recuperaran-lamine-yamal-hugo-ekitike-rodrygo-copa-del-mundo-noticia/',
    link_label: 'Depor — Estado Yamal',
    confirmed_date: 'Mayo 2026',
  },
  {
    player: 'William Saliba',
    team: 'Francia',
    flag: '🇫🇷',
    pos: 'Defensa central',
    club: 'Arsenal',
    status: 'doubt',
    injury: 'Lesión de espalda. Considerado duda para el torneo, aunque Deschamps el 3 jun declaró: "Si tuviera que jugar mañana, jugaría."',
    replacement: null,
    timeline: 'Pronóstico positivo. Debut Francia: 13 jun vs Senegal.',
    link: 'https://www.espn.com/soccer/story/_/id/48572979/2026-fifa-world-cup-injuries-tracker-which-stars-miss-latest-info',
    link_label: 'ESPN Injury Tracker — Saliba',
    confirmed_date: 'Jun 2026',
  },
  {
    player: 'Chris Richards',
    team: 'EE.UU.',
    flag: '🇺🇸',
    pos: 'Defensa central',
    club: 'Crystal Palace',
    status: 'doubt',
    injury: 'Rotura de dos ligamentos en el tobillo izquierdo. El defensa más importante del USMNT. No viajó al amistoso vs Senegal.',
    replacement: null,
    timeline: 'En rehabilitación. Reevaluación semanal. Debut USMNT: 12 jun vs Paraguay.',
    link: 'https://sports.yahoo.com/soccer/live/2026-world-cup-news-live-tracker-injuries-squads-storylines-and-updates-as-the-tournament-looms-200000653.html',
    link_label: 'Yahoo Sports — Richards USMNT',
    confirmed_date: 'Mayo–Jun 2026',
  },
  {
    player: 'Arda Güler',
    team: 'Turquía',
    flag: '🇹🇷',
    pos: 'Mediapunta',
    club: 'Real Madrid',
    status: 'doubt',
    injury: 'Lesión de isquiotibial. Gran duda para el inicio del torneo.',
    replacement: null,
    timeline: 'Posible regreso 14 jun. Debut Turquía: 15 jun vs Arabia Saudita.',
    link: 'https://www.sportsmole.co.uk/football/england/world-cup/feature/world-cup-injury-list-absent-players-and-doubts_597036.html',
    link_label: 'Sports Mole — Injury List',
    confirmed_date: 'Mayo–Jun 2026',
  },
  {
    player: 'Emiliano Martínez',
    team: 'Argentina',
    flag: '🇦🇷',
    pos: 'Portero',
    club: 'Aston Villa',
    status: 'doubt',
    injury: 'Fractura pequeña en la mano derecha sufrida en el calentamiento de la final de la Europa League con Aston Villa.',
    replacement: null,
    timeline: 'Entrena aparte. Scaloni lo monitorea. Debut Argentina: 16 jun vs Argelia.',
    link: 'https://www.infobae.com/deportes/2026/05/28/lionel-scaloni-dio-a-conocer-la-lista-de-26-convocados-de-la-seleccion-argentina-para-el-mundial-2026/',
    link_label: 'Infobae — Argentina lesionados',
    confirmed_date: 'Jun 2026',
  },
];
